# Get master key
# az functionapp keys list --resource-group quote-backend-rg --name quote-backend-function --query "masterKey"
# Or get specific function keys
# az functionapp function keys list --resource-group quote-backend-rg --name quote-backend-function --function-name QuoteHandler


### Get Quote
GET https://quote-backend-function.azurewebsites.net/api/quote?code={{FUNCTION_KEY}}

### Like Quote
POST https://quote-backend-function.azurewebsites.net/api/quote/123/like?code={{FUNCTION_KEY}}

### System Status
GET https://quote-backend-function.azurewebsites.net/api/system/status?code={{FUNCTION_KEY}}